// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARTj8CKpZiuggqzfbkh583ITfQ8crSCs0',
    appId: '1:994602820030:web:0540220692e3a2198559ef',
    messagingSenderId: '994602820030',
    projectId: 'smart-learning-2025',
    authDomain: 'smart-learning-2025.firebaseapp.com',
    storageBucket: 'smart-learning-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUckRbqiHHhbzPAVQ2zP1zwssYsRRoRCY',
    appId: '1:994602820030:android:d739d7859219be298559ef',
    messagingSenderId: '994602820030',
    projectId: 'smart-learning-2025',
    storageBucket: 'smart-learning-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE9iMPVQ6pG4KSFREA9boiH-tcgPfGfWU',
    appId: '1:994602820030:ios:19223fa3bc6b31a08559ef',
    messagingSenderId: '994602820030',
    projectId: 'smart-learning-2025',
    storageBucket: 'smart-learning-2025.firebasestorage.app',
    iosBundleId: 'com.example.smartLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE9iMPVQ6pG4KSFREA9boiH-tcgPfGfWU',
    appId: '1:994602820030:ios:19223fa3bc6b31a08559ef',
    messagingSenderId: '994602820030',
    projectId: 'smart-learning-2025',
    storageBucket: 'smart-learning-2025.firebasestorage.app',
    iosBundleId: 'com.example.smartLearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARTj8CKpZiuggqzfbkh583ITfQ8crSCs0',
    appId: '1:994602820030:web:a50fdc2b12e2e8368559ef',
    messagingSenderId: '994602820030',
    projectId: 'smart-learning-2025',
    authDomain: 'smart-learning-2025.firebaseapp.com',
    storageBucket: 'smart-learning-2025.firebasestorage.app',
  );
}
